Update zh_tw translation
SoLegendary/ageofcraft pull request #117
Opened 2024-11-09 06:32 UTC by Evilblue210

2024-11-09 06:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SoLegendary/reignofnether?pullRequest=117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SoLegendary/reignofnether?pullRequest=117) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SoLegendary/reignofnether?pullRequest=117) it.</sub>

2024-11-09 07:19 UTC, SoLegendary commented
Can you please repoint at 1.19.2-dev?

2024-11-09 07:34 UTC, Evilblue210 commented
> Can you please repoint at 1.19.2-dev?

Done

2024-11-09 09:07 UTC, notlin4 requested changes

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "fogofwar.reignofnether.chunk_bugs": "- 可能會導致區塊渲染錯誤",
```suggestion
  "fogofwar.reignofnether.chunk_bugs": "- 可能會導致區塊繪製錯誤",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "fogofwar.reignofnether.cpu_usage": "- 增加 CPU 使用率（降低區塊渲染距離有緩解）",
```suggestion
  "fogofwar.reignofnether.cpu_usage": "- 增加 CPU 使用率（降低區塊顯示距離有緩解）",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "server.reignofnether.match_reset": "本局已重置！",
```suggestion
  "server.reignofnether.match_reset": "本局已重設！",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "server.reignofnether.sync_disabled": "RTS 登入數據同步已停用。",
```suggestion
  "server.reignofnether.sync_enabled": "RTS 登入資料同步已啟用。",
  "server.reignofnether.sync_disabled": "RTS 登入資料同步已停用。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "server.resources.reignofnether.not_enough_ore": "礦石不足",
```suggestion
  "server.resources.reignofnether.not_enough_ore": "礦物不足",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "resources.reignofnether.ore": "礦石",
```suggestion
  "resources.reignofnether.ore": "礦物",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.sync_disabled2": "要解決這個問題，請聯系伺服器主啟用 RTS 同步並重新登入。",
```suggestion
  "tutorial.reignofnether.sync_disabled2": "要解決這個問題，請聯絡伺服器主啟用 RTS 同步並重新登入。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.tip.autoreturn": "提示：工人會持續採集直到您命令做其它事。當採集到至少 50 資源時會返回城鎮中心存放資源。",
```suggestion
  "tutorial.reignofnether.tip.autoreturn": "提示：工人會持續採集直到您命令做其他事。當採集到至少 50 資源時會返回城鎮中心存放資源。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.empty_pockets": "確保您的工人沒有攜帶其它資源！",
```suggestion
  "tutorial.reignofnether.empty_pockets": "確保您的工人沒有攜帶其他資源！",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.tip.sand_richer": "提示：沙漠和沙灘等沙地生態域有更多且品質高的礦石。",
```suggestion
  "tutorial.reignofnether.tip.sand_richer": "提示：沙漠和沙灘等沙地生態域擁有更多、更高品質的礦物。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.reset_game": "要重置遊戲並嘗試其他陣營，輸入 /rts-reset",
```suggestion
  "tutorial.reignofnether.reset_game": "要重設遊戲並嘗試其他陣營，輸入 /rts-reset",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.building_resources": "注意建造建築物會消耗資源。還好左上角顯示的木材和礦石資源量足夠我們建造。",
```suggestion
  "tutorial.reignofnether.building_resources": "注意建造建築物會消耗資源。還好左上角顯示的木材和礦物資源量足夠我們建造。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.gather_ore": "現在讓我們重複先前操作，來採集礦石吧。",
```suggestion
  "tutorial.reignofnether.gather_ore": "現在讓我們重複先前操作，來採集礦物吧。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.gather_food": "當您的工人在忙著採集木材和礦石時，讓我們找些食物。",
```suggestion
  "tutorial.reignofnether.gather_food": "當您的工人在忙著採集木材和礦物時，讓我們找些食物。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.hunt_pig": "就像採集木材和礦石一樣，選擇一名工人並右鍵點擊一隻動物開始打獵。",
```suggestion
  "tutorial.reignofnether.hunt_pig": "就像採集木材和礦物一樣，選擇一名工人並右鍵點擊一隻動物開始打獵。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "tutorial.reignofnether.click_ore2": "選擇任意村民，接著右鍵點擊任意礦方塊。",
```suggestion
  "tutorial.reignofnether.click_ore": "選擇一名工人，接著右鍵點擊礦物方塊。",
  "tutorial.reignofnether.click_ore2": "選擇任何一名村民，接著右鍵點擊任何礦物方塊。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.piglins.reignofnether.netherwart_farm.tooltip2": "一片地獄疙瘩田，可以種植收獲食物。",
```suggestion
  "buildings.piglins.reignofnether.netherwart_farm.tooltip2": "一片地獄疙瘩田，可以種植收穫食物。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.villagers.reignofnether.wheat_farm.tooltip2": "一片小麥田，可以種植收獲食物。",
```suggestion
  "buildings.villagers.reignofnether.wheat_farm.tooltip2": "一片小麥田，可以種植收穫食物。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.monsters.reignofnether.pumpkin_farm.tooltip2": "一片南瓜田，可以種植收獲食物。",
```suggestion
  "buildings.monsters.reignofnether.pumpkin_farm.tooltip2": "一片南瓜田，可以種植收穫食物。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.monsters.reignofnether.laboratory.tooltip1": "一座邪惡實驗室，可基於己建造的其它建築物研究新科技。",
```suggestion
  "buildings.monsters.reignofnether.laboratory.tooltip1": "一座邪惡實驗室，可基於已建造的其他建築物研究新科技。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "abilities.reignofnether.connect_portal.tooltip1": "連接到其它您建造的運輸傳送門。",
```suggestion
  "abilities.reignofnether.connect_portal.tooltip1": "連接到其他您建造的運輸傳送門。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "building.reignofnether.too_close": "太靠近其它建築物",
```suggestion
  "building.reignofnether.too_close": "太靠近其他建築物",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.monsters.reignofnether.spruce_bridge.tooltip2": "必須連接陸地或其它橋。",
```suggestion
  "buildings.monsters.reignofnether.spruce_bridge.tooltip2": "必須連接陸地或其他橋。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.piglins.reignofnether.blackstone_bridge.tooltip2": "必須連接陸地或其它橋。",
```suggestion
  "buildings.piglins.reignofnether.blackstone_bridge.tooltip2": "必須連接陸地或其他橋。",
```

2024-11-09 09:07 UTC, notlin4 commented on src/main/resources/assets/reignofnether/lang/zh_tw.json
> +  "buildings.villagers.reignofnether.oak_bridge.tooltip2": "必須連接陸地或其它橋。",
```suggestion
  "buildings.villagers.reignofnether.oak_bridge.tooltip2": "必須連接陸地或其他橋。",
```

2024-11-10 09:13 UTC, SoLegendary approved these changes

2024-11-10 09:13 UTC, merged