[1.0.8] feat: update zh_cn
SoLegendary/ageofcraft pull request #120
Opened 2024-11-09 09:00 UTC by NumberSir

2024-11-09 09:46 UTC, maaaxinfinity requested changes
![image](https://github.com/user-attachments/assets/15472c0c-48f1-4ae6-8f46-f10453bed79b)
这里可以把“使它们”改成“使其” 简化表达

2024-11-09 09:46 UTC, maaaxinfinity commented on src/main/resources/assets/reignofnether/lang/zh_cn.json
> +  "ability.reignofnether.enchant.maiming.tooltip2": "使被击中的单位迟缓一段时间。",
建议改为"对击中的单位造成一段时间的缓慢效果。"

2024-11-09 09:46 UTC, maaaxinfinity commented on src/main/resources/assets/reignofnether/lang/zh_cn.json
> +  "abilities.reignofnether.spin_webs.tooltip1": "朝地面上吐出一块黏腻蛛网",
我觉得还是 粘性蛛网或者蜘蛛网 更好一点吧

2024-11-09 09:46 UTC, maaaxinfinity commented on src/main/resources/assets/reignofnether/lang/zh_cn.json
> +  "ability.reignofnether.enchant.vigor": "魔咒：活力",
活化感觉也不错

2024-11-09 09:46 UTC, maaaxinfinity commented on src/main/resources/assets/reignofnether/lang/zh_cn.json
> +  "ability.reignofnether.enchant.error2": "单位未在有效范围内",
可以加上限定 该单位或者所选单位 未在有效范围内

2024-11-09 09:56 UTC, NumberSir commented on src/main/resources/assets/reignofnether/lang/zh_cn.json
> +  "ability.reignofnether.enchant.vigor": "魔咒：活力",
参考了植物魔法中的同名魔咒

2024-11-10 08:53 UTC, SoLegendary approved these changes

2024-11-10 08:53 UTC, merged